import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.models as models
import numpy as np
import os
import matplotlib.pyplot as plt
import pandas as pd
from tqdm import tqdm
from rsna_dataset import JpegRSNADataset, val_transforms, IMAGENET_MEAN, IMAGENET_STD
from deconv import DeconvNet

def load_trained_model(model_path, device):
    print(f"Loading model from {model_path}...")
    model = models.resnet34(weights=None)
    num_ftrs = model.fc.in_features
    model.fc = nn.Linear(num_ftrs, 2)
    
    if os.path.exists(model_path):
        checkpoint = torch.load(model_path, map_location=device)
        
        
        if isinstance(checkpoint, dict) and 'net' in checkpoint:
            state_dict = checkpoint['net']
        elif isinstance(checkpoint, dict) and 'model' in checkpoint:
            state_dict = checkpoint['model']
        elif isinstance(checkpoint, dict) and 'state_dict' in checkpoint:
            state_dict = checkpoint['state_dict']
        else:
            state_dict = checkpoint
            
        
        new_state_dict = {}
        for k, v in state_dict.items():
            
            if k == 'iter':
                continue
                
            # Skip non-tensor data (metadata)
            if not isinstance(v, torch.Tensor):
                continue
            
            # --- FIX 3: Strip 'backbone.' prefix generated by Resnet34Pneu ---
            name = k.replace("backbone.", "")
            
            # Check for shape mismatch (e.g., fc layer 1000 vs 2 classes)
            if name in model.state_dict():
                if v.shape != model.state_dict()[name].shape:
                    print(f"Warning: Skipping {name} due to shape mismatch: {v.shape} vs {model.state_dict()[name].shape}")
                    continue
            new_state_dict[name] = v
            
        msg = model.load_state_dict(new_state_dict, strict=False)
        print(f"Model loaded with keys: {len(new_state_dict)}. Missing: {len(msg.missing_keys)}")
    else:
        raise FileNotFoundError(f"Model not found at {model_path}")
        
    model = model.to(device)
    model.eval()
    return model

def compute_co_score(model, x, y0, attr, submethod='sum'):
    """
    Calculate Confidence Optimization (CO) Score.
    
    Args:
        model: Trained PyTorch model.
        x: Input tensor [1, C, H, W].
        y0: Ground truth label index (int).
        attr: Attribution map tensor [1, C, H, W].
        submethod: 'sum' (x + attr) or 'mult' (x * attr).
        
    Returns:
        co_score: The calculated score.
        y_pred: The predicted class index of the original image.
    """
    # Normalize attribution to [-1, 1] based on max absolute value
    if attr.abs().max() > 0:
        attr = attr / attr.abs().max()
    
    with torch.no_grad():
        # 1. Original prediction
        logits = model(x) # [1, NumClasses]
        probs = F.softmax(logits, dim=1) # Use probabilities for Confidence
        n_class = probs.shape[1]
        y_pred = torch.argmax(probs, dim=1).item()
        
        # 2. Augmented prediction
        if submethod == 'sum':
            # GAX: Add attribution to input (Gradient Ascent)
            # Scale attr by alpha to avoid over-perturbation
            alpha = 0.25
            y_aug_logits = model(x + (attr * alpha))
            y_aug_probs = F.softmax(y_aug_logits, dim=1)
        elif submethod == 'mult':
            # Handle normalization before multiplication
            # 1. Denormalize x to [0, 1] range
            mean = torch.tensor(IMAGENET_MEAN).view(1, 3, 1, 1).to(x.device)
            std = torch.tensor(IMAGENET_STD).view(1, 3, 1, 1).to(x.device)
            x_denorm = x * std + mean
            
            # 2. Apply attribution (masking) in valid pixel space
            # Use Absolute Value for mask to keep pixels with high influence
            mask = torch.abs(attr)
            if mask.max() > 0:
                mask = mask / mask.max() # Normalize to [0, 1]
            
            x_aug_denorm = x_denorm * mask
            
            # 3. Renormalize for the model
            x_aug = (x_aug_denorm - mean) / std
            y_aug_logits = model(x_aug)
            y_aug_probs = F.softmax(y_aug_logits, dim=1)
        else:
            raise ValueError(f"Unknown submethod: {submethod}")
            
        # 3. CO Score calculation
        # Construct score constants: +1 for ground truth class, -1/(N-1) for others
        score_constants = torch.zeros_like(probs) - (1.0 / (n_class - 1))
        score_constants[0, y0] = 1.0
        
        # Formula: (y_aug - y) * score_constants
        co_score = (y_aug_probs - probs) * score_constants
        co_score = torch.sum(co_score).item()
        
    return co_score, y_pred

def main():
    # Settings
    root_dir = "jpeg_dataset"
    model_path = os.path.join("checkpoints", "best_resnet34_v3.pth")
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    
    # Setup output directories for GAX artifacts
    heatmap_dir = os.path.join("results", "heatmaps")
    os.makedirs(heatmap_dir, exist_ok=True)
    
    # 1. Load Dataset
    test_dataset = JpegRSNADataset(root_dir=root_dir, split="test", transform=val_transforms)
    print(f"Dataset size: {len(test_dataset)}")
    
    # 2. Load Model
    try:
        model = load_trained_model(model_path, device)
    except FileNotFoundError as e:
        print(e)
        return

    # 3. Initialize DeconvNet
    deconv = DeconvNet(model)
    
    # Storage for results
    results = {
        'sum': {'correct': [], 'wrong': []},
        'mult': {'correct': [], 'wrong': []}
    }
    
    # List to store detailed CSV data
    csv_data = []
    
    print("Collecting CO scores using Deconvolution...")
    
    # 4. Iterate through dataset
    for i in tqdm(range(len(test_dataset)), desc="Processing"):
        img, label = test_dataset[i]
        path, _ = test_dataset.samples[i]
        patient_id = os.path.splitext(os.path.basename(path))[0]
        
        img = img.unsqueeze(0).to(device) # [1, C, H, W]
        label_idx = label.item()
        
        # A. Get Prediction to determine which class to explain
        with torch.no_grad():
            logits = model(img)
            pred_idx = logits.argmax(dim=1).item()
            
        # B. Generate Deconv Map for the PREDICTED class
        img_for_attr = img.clone().detach()
        attr_np = deconv.generate(img_for_attr, target_class=pred_idx)
        
        # --- GAX ARTIFACT GENERATION ---
        np.save(os.path.join(heatmap_dir, f"{patient_id}.npy"), attr_np)
        
        # Convert numpy result back to tensor [1, C, H, W]
        attr = torch.from_numpy(attr_np).unsqueeze(0).to(device)
        
        # C. Compute CO Scores for both submethods
        row_data = {
            'patient_id': patient_id,
            'true_label': label_idx,
            'pred_label': pred_idx,
            'correct': (label_idx == pred_idx)
        }
        
        for submethod in ['sum', 'mult']:
            score, y_pred_idx = compute_co_score(model, img, label_idx, attr, submethod)
            
            key = 'correct' if y_pred_idx == label_idx else 'wrong'
            results[submethod][key].append(score)
            row_data[f'co_score_{submethod}'] = score
            
        csv_data.append(row_data)
            
    # Clean up hooks
    deconv.remove_hooks()
    
    # Save detailed results to CSV
    df = pd.DataFrame(csv_data)
    csv_path = os.path.join("results", "co_scores.csv")
    df.to_csv(csv_path, index=False)
    print(f"Detailed scores saved to {csv_path}")
    print(f"Heatmaps saved to {heatmap_dir}")
    
    # 5. Visualize Results
    plot_results(results)

def plot_results(results):
    """Generates boxplots for the collected CO scores."""
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    
    for idx, submethod in enumerate(['sum', 'mult']):
        ax = axes[idx]
        data_correct = results[submethod]['correct']
        data_wrong = results[submethod]['wrong']
        
        data_to_plot = []
        labels = []
        
        if data_correct:
            data_to_plot.append(data_correct)
            labels.append(f'Correct\n(n={len(data_correct)})')
        if data_wrong:
            data_to_plot.append(data_wrong)
            labels.append(f'Wrong\n(n={len(data_wrong)})')
            
        if data_to_plot:
            ax.boxplot(data_to_plot, labels=labels, showfliers=False)
            ax.set_title(f'CO Scores ({submethod})')
            ax.set_ylabel('CO Score')
            ax.grid(True, linestyle='--', alpha=0.7)
            ax.axhline(y=0, color='r', linestyle='-', linewidth=1, alpha=0.5) 
            
            for i, d in enumerate(data_to_plot):
                mean_val = np.mean(d)
                ax.text(i+1, mean_val, f'{mean_val:.3f}', 
                        ha='center', va='bottom', fontweight='bold', color='blue')
        else:
            ax.text(0.5, 0.5, 'No data', ha='center')
            
    plt.suptitle("Confidence Optimization (CO) Scores - Deconvolution")
    plt.tight_layout()
    
    os.makedirs("results", exist_ok=True)
    
    base_name = "co_scores_boxplot"
    extension = ".png"
    save_path = os.path.join("results", base_name + extension)
    
    counter = 1
    while os.path.exists(save_path):
        save_path = os.path.join("results", f"{base_name}{counter}{extension}")
        counter += 1

    plt.savefig(save_path)
    print(f"Plot saved to {save_path}")
    plt.show()

if __name__ == "__main__":
    main()